/**
 * Developer Mode Skill (Part 5)
 * ------------------------------------------------------------------
 * Optional, opt-in assistance for development tasks that can be done safely
 * in the browser:
 *   - explain code (heuristic analysis: structure, complexity)
 *   - find common programming errors (bracket balance, TODO/FIXME, common bugs)
 *   - suggest fixes for those detected issues
 *   - scaffold project files (downloads a small, ready-to-run template)
 *   - read logs (paste-in log text is parsed for errors/warnings)
 *   - "run" a command (simulated; real shell execution is out of scope for
 *     a client-side page and is explicitly not enabled)
 *
 * Never executes dangerous or destructive commands. Command execution is
 * simulated only.
 *
 * Permission enforcement is centralized: "run" is declared in
 * sensitiveActions, so the permission gateway (skillManager.executeByName
 * → permissions.gate) confirms it before this skill runs. The skill
 * itself never prompts.
 */
import { state } from '../state.js';

export const dev = {
    name: 'dev',
    description: 'Developer assistance: explain code, find bugs, scaffold projects',
    risk: 'medium',
    permissions: ['dev.read-files', 'dev.scaffold'],
    inputs: [
        { name: 'code', type: 'text', description: 'Code or logs to analyze' }
    ],
    actions: ['explain', 'find-errors', 'scaffold', 'read-logs', 'run'],
    // Simulated command execution still surfaces a confirmation so the
    // user knows what will "run".
    sensitiveActions: [
        { pattern: /\brun\b/i, reason: 'runs a command (simulated — ALICE never executes real shell commands)' }
    ],
    patterns: [
        /explain\s+(?:this\s+)?code/i,
        /(?:find|check|look\s+for)\s+(?:the\s+)?(?:bug|bugs|error|errors|issue|problem)/i,
        /debug\s+(?:this\s+)?(?:code|script)/i,
        /create\s+(?:a\s+)?(?:new\s+)?project/i,
        /scaffold\s+(?:a\s+)?project/i,
        /read\s+(?:the\s+)?logs?/i,
        /analy[sz]e\s+(?:the\s+)?logs?/i,
        /run\s+(?:the\s+)?(?:command|script|test|build)/i,
        /fix\s+(?:the\s+)?(?:error|bug|issue)/i,
        /developer\s+mode/i
    ],

    async execute(input, context = {}) {
        const text = input.toLowerCase();

        if (text.includes('scaffold') || text.includes('new project') || text.includes('create a project')) {
            return this._scaffold();
        }

        if (text.includes('log')) {
            return this._readLogs();
        }

        if (text.includes('run')) {
            return this._runCommand(input);
        }

        // explain / find bugs / fix → paste-in code analysis
        return this._analyzeCode(text);
    },

    /**
     * Scaffold a minimal, dependency-free project and download it.
     */
    _scaffold() {
        const files = {
            'index.html': `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>ALICE Project</title>\n</head>\n<body>\n  <h1>Hello from ALICE</h1>\n  <script src="app.js"></script>\n</body>\n</html>\n`,
            'app.js': `// Generated by ALICE Developer Mode\nconsole.log('Project scaffolded by ALICE');\n`,
            'README.md': `# ALICE Project\nScaffolded by ALICE Developer Mode. No dependencies required.\n`
        };

        // Download each file
        for (const [name, content] of Object.entries(files)) {
            const blob = new Blob([content], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = name;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        }

        state.logActivity('Scaffolded project (3 files)', 'success');
        return {
            success: true,
            result: 'Scaffolded a minimal project: index.html, app.js, and README.md. The downloads should start automatically.'
        };
    },

    /**
     * Read and summarize pasted log text (or a file the user selects).
     */
    _readLogs() {
        // Offer a file picker, plus fall back to reading last activity logs
        const inputEl = document.createElement('input');
        inputEl.type = 'file';
        inputEl.accept = '.log,.txt,.out';

        inputEl.onchange = async (e) => {
            const file = e.target.files && e.target.files[0];
            if (!file) return;
            const text = await file.text();
            const analysis = this._analyzeLogs(text);
            state.logActivity(`Logs analyzed: ${analysis.errors} errors, ${analysis.warnings} warnings`, 'success');
            state.notify(`Logs: ${analysis.errors} errors, ${analysis.warnings} warnings`, 'info');
        };

        inputEl.click();

        return {
            success: true,
            interactive: true,
            result: 'Please select a log file to analyze. I will count errors and warnings and surface notable lines.'
        };
    },

    _analyzeLogs(text) {
        const lines = text.split(/\r?\n/);
        const errors = lines.filter(l => /\b(error|fatal|exception|traceback|failed)\b/i.test(l));
        const warnings = lines.filter(l => /\b(warn|warning|deprecated)\b/i.test(l));
        return { errors: errors.length, warnings: warnings.length, errorLines: errors.slice(0, 5) };
    },

    /**
     * Simulated command execution (never real). Confirmed upstream by the
     * permission gateway ("run" is a sensitive action).
     */
    _runCommand(input) {
        const cmd = input.replace(/run\s+(?:the\s+)?(?:command|script|test|build)\s*/i, '').trim() || 'unknown command';

        return {
            success: true,
            result: `Simulated "${cmd}" successfully. Note: ALICE does not execute real shell commands for safety — this is a dry-run.`
        };
    },

    /**
     * Heuristic code analysis: explain structure, find common issues,
     * and suggest fixes.
     */
    _analyzeCode(input) {
        // Reuse the last document if code was pasted via reader, otherwise
        // prompt the user to paste code (we can't read arbitrary local files
        // without a picker).
        const lastDoc = state.get('lastReadDocument');
        if (!lastDoc || !lastDoc.content) {
            return {
                success: true,
                interactive: true,
                result: 'Paste or read the code first (say "read a document"), then ask me to explain it or find bugs.'
            };
        }

        const code = lastDoc.content;
        const issues = this._detectIssues(code);
        const stats = this._describe(code);

        let response = `Code overview: ${stats.lines} lines, ${stats.functions} function(s).`;
        if (issues.length) {
            response += ` I found ${issues.length} potential issue(s): ` +
                issues.slice(0, 3).map(i => `"${i.message}" (suggested fix: ${i.fix})`).join('; ') + '.';
        } else {
            response += ' No common issues detected.';
        }

        return { success: true, result: response, issues, stats };
    },

    _detectIssues(code) {
        const issues = [];

        // Unbalanced braces/brackets/parens
        for (const [open, close, name] of [['{', '}', 'brace'], ['(', ')', 'parenthesis'], ['[', ']', 'bracket']]) {
            const count = (code.match(new RegExp('\\' + open, 'g')) || []).length -
                          (code.match(new RegExp('\\' + close, 'g')) || []).length;
            if (count !== 0) {
                issues.push({
                    message: `unbalanced ${name}s (${count > 0 ? 'missing' : 'extra'} "${count > 0 ? close : open}")`,
                    fix: `check that every "${open}" has a matching "${close}"`
                });
            }
        }

        // TODO/FIXME
        const todos = code.match(/\/\/\s*(TODO|FIXME|HACK)/g) || [];
        if (todos.length) {
            issues.push({ message: `${todos.length} TODO/FIXME marker(s)`, fix: 'review and resolve the marked sections' });
        }

        // Common bugs: single '=' inside a condition (== vs = confusion)
        if (/if\s*\([^)]*[^<>=!]=[^=]/.test(code)) {
            issues.push({ message: 'possible assignment inside a condition (== vs =)', fix: 'use === for comparison' });
        }
        if (/console\.log\([^)]*\)/i.test(code) && code.includes('//') === false) {
            // only flag if many logs
            const logs = (code.match(/console\.log/g) || []).length;
            if (logs > 5) issues.push({ message: `${logs} console.log statements`, fix: 'remove debug logging before shipping' });
        }
        if (/\bvar\s+[A-Za-z_$][A-Za-z0-9_$]*\s*=/.test(code)) {
            issues.push({ message: 'uses var (function-scoped)', fix: 'prefer let or const' });
        }

        return issues;
    },

    _describe(code) {
        const lines = code.split(/\r?\n/).length;
        const functions = (code.match(/function\s+[A-Za-z0-9_$]+\s*\(/g) || []).length +
                          (code.match(/[A-Za-z0-9_$]+\s*=\s*(?:\([^)]*\)\s*=>|async\s*\()/g) || []).length;
        return { lines, functions };
    },

    onError(input, result) {
        return {
            success: false,
            error: `${result.error || 'Developer action failed'}. Read a code file first, then ask me to explain it or find bugs.`
        };
    }
};
